### ISSUE TITLE
xef-gcp - Runtime

### ISSUE THREAD

**Issue by jackcviers** [xebia-functional/xef#291] opened 2023-08-02 04:05 UTC
Using the api overview (https://cloud.google.com/vertex-ai/docs/generative-ai/model-reference/overview) and the available embeddings, create a xef gcp runtime similar to that for xef-openai that sets sensible defaults, initializes the client, and implements the client dsl.

Depends on  #290

**Comment by Intex32** [comment] 2023-09-06 08:36
Duplicate of #371 ?

**Comment by anamariamv** [comment] 2023-09-06 09:47
Solved #371

**Closed by anamariamv** 2023-09-06 09:47 UTC
